In [3]:
import numpy as np
list1 = [1,2,3]
vec = np.array(list1)
print(list1)
print(vec)

[1, 2, 3]
[1 2 3]


In [2]:
list2 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
mat = np.array(list2)
print(list2)
print(mat)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
print(vec.ndim)
print(mat.ndim)

1
2


In [5]:
print(vec.shape)
print(mat.shape)

(3,)
(3, 5)


In [7]:
vec2 = np.array([[1,2,3]])
vec3 = np.array([[1],[2],[3]])
print(vec2.shape)
print(vec3.shape)

(1, 3)
(3, 1)


In [8]:
print(mat.shape)
# (3, 5)
# 3: sample의 수, 행의 수
# 5: feature(특징)의 수, 열의 수

(3, 5)


In [9]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
# indexing
mat[1,2]

8

In [19]:
# slicing (범위)
# a:b -> index a부터 index b-1까지
# :b -> index 0(처음)부터 index b-1까지
# a: -> index a부터 마지막 index까지
# : -> 모든 index
# -1 -> 마지막 index
print(mat[1:,:3])

[[ 6  7  8]
 [11 12 13]]


In [25]:
# 2차원  ndarray mat에서
# mat[a,b] -> 원소 하나의 값, ndim = 0
# mat[a,범위] or mat[범위,a] -> 하나의 index는 범위, 하나의 index는 숫자 지정, ndim = 1
# mat[범위,범위] -> 행과 열 모두 index 범위일 경우, ndim = 2
print(mat[0,:3].shape)
print(mat[:1,:3].shape)
print(mat[:,1].shape)
print(mat[:,1:2].shape)

(3,)
(1, 3)
(3,)
(3, 1)


In [27]:
print(vec)
print(vec.reshape(3,1))
print(vec.reshape(1,3))
# ndarray.reshape(): ndarray와 reshape한 결과의 원소 수는 반드시 동일해야 한다.

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]


In [28]:
print(mat.shape)
print(mat.reshape(15,1))
print(mat.reshape(5,-1))

(3, 5)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [31]:
vec3 = np.array([1,2,3,4,5])
# 1d array를 2d array로 변경
print(vec3)
print(vec3.reshape(1,5))
print(vec3.reshape(5,1))
print(vec3.reshape(1,-1))
print(vec3.reshape(-1,1))

[1 2 3 4 5]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [34]:
vec4 = np.array([[n] for n in range(1,6)])
print(vec4)
print(vec4.reshape(-1))
print(vec4.ravel())

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[1 2 3 4 5]


In [37]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8,9],[10,11,12]])
print(mat1)
print(mat2)
print(mat1.shape)
print(mat2.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
(2, 3)
(2, 3)


In [39]:
# 행 또는 열, 원소 삭제
print(np.delete(mat1, 0))
# np.delete(ndarray, a) -> ndarray를 1열로 나열한 뒤(1d array), index a 원소 삭제
# -> 결과는 1차원

# 행 또는 열을 삭제하기 위해서는 axis를 지정해야 함
print(np.delete(mat1, 1, axis=0))
print(np.delete(mat1, 1, axis=1))

[2 3 4 5 6]
[[1 2 3]]
[[1 3]
 [4 6]]


In [41]:
print(np.concatenate((mat1, mat2)))
# axis default value is 0
print(np.concatenate((mat1, mat2), axis=0))
print(np.concatenate((mat1, mat2), axis=1))
# axis - 0: 행 결합, 1: 열 결합

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
