In [1]:
import numpy as np

### 1. 입력

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
x.shape
# (4,2): feature(특징)이 2개인 4개의 sample

(4, 2)

### 2. Perceptron 정의

In [3]:
def perceptron(x, w, b):
    # 입력 x, w는 ndarray
    # w1x1 + w2x2는 w벡터와 x벡터의 내적
    return (x.dot(w)+b > 0).astype('int32') # 반환하는 값이 bool type인 ndarray이므로 astype()로 data type 변경

In [4]:
w = np.array([3,2])
b = 3
perceptron(x, w, b)

array([1, 1, 1, 1])

#### 2-1. AND

In [5]:
def AND(x_and):
    w_and = np.array([3,4])
    b_and = -5
    return perceptron(x_and, w_and, b_and)

AND(x)

array([0, 0, 0, 1])

#### 2-2. NAND

In [6]:
def NAND(x_nand):
    w_nand = np.array([-3,-4])
    b_nand = 5
    return perceptron(x_nand, w_nand, b_nand)

NAND(x)

array([1, 1, 1, 0])

#### 2-3. OR

In [7]:
def OR(x_or):
    w_or = np.array([0.5,0.5])
    b_or = -0.3
    return perceptron(x_or, w_or, b_or)

OR(x)

array([0, 1, 1, 1])

### 3. 결과 확인

In [8]:
# 입력 순서: [0,0], [0,1], [1,0], [1,1]
print('[AND]:  ', AND(x))
print('[NAND]: ', NAND(x))
print('[OR]:   ', OR(x))

[AND]:   [0 0 0 1]
[NAND]:  [1 1 1 0]
[OR]:    [0 1 1 1]


### 4. XOR (multi-layer perceptron)

In [11]:
def XOR(x_xor):
    s1 = NAND(x_xor).reshape(-1,1)
    s2 = OR(x_xor).reshape(-1,1)
    in_and = np.concatenate((s1, s2), axis=1)
    return AND(in_and)

XOR(x)

array([0, 1, 1, 0])